=== ashim-dhungana/WebDev-Learn/XML/question4.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="purchaseOrder">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="order">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="orderDate"></xs:element>

                            <xs:element name="shippingAddress">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="houseNumber"></xs:element>
                                        <xs:element name="streetName"></xs:element>
                                        <xs:element name="city"></xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="billingAddress">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="houseNumber"></xs:element>
                                        <xs:element name="streetName"></xs:element>
                                        <xs:element name="city"></xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="items">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="item">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="itemName"></xs:element>
                                                    <xs:element name="quantity"></xs:element>
                                                    <xs:element name="price"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="itemId" type="xs:integer"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="paid" type="xs:positiveInteger"></xs:attribute>

                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ashim-dhungana/WebDev-Learn/XML/9.question4.xml
<?xml version="1.0" encoding="UTF-8"?>

<purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="question4.xsd">

    <order paid="1">

        <orderDate></orderDate>

        <shippingAddress>
            <houseNumber></houseNumber>
            <streetName></streetName>
            <city></city>
        </shippingAddress>

        <billingAddress>
            <houseNumber></houseNumber>
            <streetName></streetName>
            <city></city>
        </billingAddress>

        <items>
            <item itemId="7">
                <itemName></itemName>
                <quantity></quantity>
                <price></price>
            </item>
        </items>

    </order>

</purchaseOrder>


<!-- a. purchaseOrder can have only one order with mandatory attribute ‘poid’ of
integer type
b. purchaseOrder must have orderDate, shippingAddress, billingAddress and items
c. orderDate must be of Date Type
d. shippingAddress and billingAddress must have the elements: houseNumber,
streetName and city sequentially.
e. items must come at least once to maximum 20 times
f. items contains item that have itemName, quantity, and price.
g. item must have ‘itemId’ attribute of integer type
h. Maximum quantity of item should not be greater than 100
i. itemPrice should not be negative.

Write XSLT to show data in following styles:
d. Price: if price > 100 then Product Name font-color: GREEN else font-color: RED
e. Sort the Purchase order records using “quantity” in descending order. -->
