=== ashim-dhungana/WebDev-Learn/XML/question2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Order">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Shiporder">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="Orderby">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Ordername"></xs:element>
                                        <xs:element name="Orderphone"></xs:element>
                                        <xs:element name="Orderdate"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="Shipto">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="Name"></xs:element>

                                        <xs:element name="Shipaddress">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Street"></xs:element>
                                                    <xs:element name="Houseno"></xs:element>
                                                    <xs:element name="VDC"></xs:element>
                                                    <xs:element name="Municipality"></xs:element>
                                                    <xs:element name="City"></xs:element>
                                                    <xs:element name="District"></xs:element>
                                                    <xs:element name="Country"></xs:element>
                                                    <xs:element name="Postalcode"></xs:element>
                                                    <xs:element name="Telephone"></xs:element>
                                                    <xs:element name="Mobile"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                                
                            <xs:element name="Orderitem">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Itemnumber"></xs:element>
                                        <xs:element name="Itemname"></xs:element>
                                        <xs:element name="Itemnote"></xs:element>
                                        <xs:element name="ItemInsurance"></xs:element>
                                        <xs:element name="Itemquantity"></xs:element>
                                        <xs:element name="Currency"></xs:element>
                                        <xs:element name="Itemunitprice"></xs:element>
                                        <xs:element name="Shipcharge"></xs:element>
                                        <xs:element name="Totalprice"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ashim-dhungana/WebDev-Learn/XML/7.question2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Order
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="question2.xsd">

    <Shiporder orderid="1">

        <Orderby>
            <Ordername></Ordername>
            <Orderphone>987654321</Orderphone>
            <Orderdate>2024-08-01</Orderdate>
        </Orderby>

        <Shipto>
            <Name></Name>

            <Shipaddress>
                <Street></Street>
                <Houseno></Houseno>
                <Municipality></Municipality>
                <City></City>
                <District></District>
                <Country></Country>
                <Postalcode>1234567891</Postalcode>
                <Telephone>12345678</Telephone>
                <Mobile>123456789</Mobile>
            </Shipaddress>

        </Shipto>

        <Orderitem>
            <Itemnumber>77</Itemnumber>
            <Itemname></Itemname>
            <Itemnote></Itemnote>
            <ItemInsurance>Yes</ItemInsurance>
            <Itemquantity>5</Itemquantity>
            <Currency>USD</Currency>
            <Itemunitprice>45.6</Itemunitprice>
            <Shipcharge>4.4</Shipcharge>
            <Totalprice>50.0</Totalprice>
        </Orderitem>

    </Shiporder>


</Order>


<!-- Validation Rules:
-
 Use the data type as the Element name suggests. Elements must appear in
proper sequence.
-
 Shiporder & Orderitem can appear multiple times.
-
 Orderid & Postalcode must not contain more than 10 characters & it must be
positive integer.
-
 ‘Telephone’ & ‘Mobile’ must be 7 to 15 character long positive integer.
-
 Either one child element or another can appear in case of VDC & Municipality.
If no country is specified ‘Nepal’ should be placed.
-
 ‘Itemnote’ is optional. Currency must contain 3 characters, uppercase A-Z.
-
 ‘ItemInsurance’ contains data either ‘Yes’ or ‘No’. -->
